### ISSUE TITLE
halSummarizeMutations evolverMammalsLoci1.hal

### ISSUE THREAD

**Issue by ashlingcha** [ComparativeGenomicsToolkit/hal#102]
When I use halSummarizeMutations I get the error segmentation fault (core dumped) - think this may be a bug?

Thanks,
Ashling

**Comment by brettChapman** [comment]
I'm getting the same error as well. Looks like its been an issue since 2016:
https://github.com/ComparativeGenomicsToolkit/hal/issues/48

Someone mentioned removing "-" and "." characters from the sequence file name and fasta headers, but I have none of those, only underscores "_", same as the evolverMammals example.

@glennhickey @diekhans Is this a known bug? Any workarounds? Thanks.

**Comment by brettChapman** [comment]
@glennhickey thanks for fixing. I'm running from docker. I noticed that the fix isn't implemented in the cactus build on docker though: quay.io/comparative-genomics-toolkit/cactus

However, when I install the comparative-genomics-toolkit from the Dockerfile it works fine with no segfault on exiting.

How often does the Docker image of Cactus get updated? Thanks.

**Comment by glennhickey** [comment]
This will make it into Cactus when
https://github.com/ComparativeGenomicsToolkit/cactus/pull/265 is merged in,
which will hopefully be soon.

We're about due for a new Cactus release, so we'll definitely make a docker
image then.

There are millions of non-release images generated automatically.  It makes
one each time the latest commit in master is changed, as well as for any
commits within a PR.

**Comment by diekhans** [comment]
The main pending thing for a release is getting hal python
properly installed.  Last I had time to look at, it was seeming
like HAL needed a setup.py; however maybe tricking cactus
setup.py would do it easier.  Depedencies that are not in pypi
are not as straight forward.
