### ISSUE TITLE
Self-link causes warnings on kubernetes

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/hal#144]
I'm not sure what command causes it, but I have a failing script that gives this while copying from aws
```
warning: Skipping file /cactus/submodules/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal/hal. File does not exist.
```

And sure enough, hal's Makefile seems to be doing this deliberately:
https://github.com/ComparativeGenomicsToolkit/hal/blob/master/Makefile#L25-L28

Perhaps we can refactor to get the python modules to work without a recursive directory structure?  It seems like this is dangerous for any code that may be traversing the directory tree.

**Comment by diekhans** [comment]
I put that in deliberately so test could be easily run.  Part of
the problem is that there are assumption about the checkout
directory is the module, so if you checkout to a name other than
hal, things break (I do this to keep multiple version).

Easy fix is to remove this when tests complete.

Better fix is to make all the models good python citizens.

Also, recursive copies shouldn't normally flow symlinks by
default, that is generally asking for a lot of stuff.

I will put in the easy fix now.
