### ISSUE TITLE
Missing configuration file?

### ISSUE THREAD

**Issue by J-Calvelo** [ComparativeGenomicsToolkit/hal#152]
Sorry for the inconvenience but I'm trying to build the latest version and run halSynteny but the configure file seems to be missing. The older hdf5-1.10.1 works fine.

Thanks

**Comment by glennhickey** [comment]
Could you be more specific?  Which configure file is missing?  Which error
are you getting?

If you are getting a new build error after updating hal, it could be due to
sonLib.  hal has been changed to depend on a recent version of sonLib from
here: https://github.com/ComparativeGenomicsToolkit/sonLib (I don't think
it works with https://github.com/benedictpaten/sonLib any longer)

**Comment by J-Calvelo** [comment]
I was trying to build it from scratch. Likely I'm just confused, here is what I tried: 

git clone https://github.com/ComparativeGenomicsToolkit/hal.git
cd hal
./configure --enable-cxx
`-bash: ./configure: No such file or directory`

Of course make doesn't works after:
```include.mk:35: ../sonLib/include.mk: No such file or directory
make: *** No rule to make target '../sonLib/include.mk'.  Stop.```

**Comment by glennhickey** [comment]
Before building hal with `make` you have to install hdf5 and sonLib.  There are instructions for doing so in the [README](https://github.com/ComparativeGenomicsToolkit/hal#installing-dependencies)

HAL is also included in Cactus, which has a [release you can download](https://github.com/ComparativeGenomicsToolkit/cactus/releases)
