### ISSUE TITLE
Is it possible to get all the pairwise mapping position by hal2paf?

### ISSUE THREAD

**Issue by Secretloong** [ComparativeGenomicsToolkit/hal#190]
I have tried to convert the `HAL` alignments to a `GFA` file as following:
```
hal2fasta 21sp.hal $(halStats --root 21sp.hal) --subtree --upper --ucscSequenceNames > test.fa
hal2paf 21sp.hal > test.paf
seqwish -p test.paf -s test.fa -g test.gfa
```
But there are too many short (1bp) segments in `GFA`. Then I found the `PAF` file only include the pairwise mapping positions between parent node and children nodes. Otherwise the path lines in 'GFA' suggest that many parent genomes have been splited to small segments.

I suppose the incomplete pairwise (not all-vs-all) mapping information in 'PAF' causes this issue. So is it possible to extract all-vs-all pairwise mapping positions by 'hal2paf'?

**Comment by glennhickey** [comment]
The correct way to make a GFA from hal is [hal2vg](https://github.com/ComparativeGenomicsToolkit/hal2vg/releases) then [vg view](https://github.com/vgteam/vg/releases/tag/v1.30.0).

`hal2paf` indeed only writes child/parent alignments from the HAL.  While in theory this information specifies the entire alignment, because `seqwish` only considers exact matches, information does get lost.  For example in a column like this:
```
Ancestor:   A
Child1:     A
Child2:     C
Child3:     C
Child4:     A
```
`hal2paf` will write the 4 pairwise alignments, one for each child to the ancestor.  But because `seqwish` only considers exact matches, it will ignore the alignments for Child2 and Child3.  And in the resulting GFA there will be two separate `C` nodes and one `A` node.  `hal2vg` will not have this issue.  

It's not quite in a released yet, [but vg/GFA output will be available directly from the cactus scripts soon](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md)

**Comment by Secretloong** [comment]
Awesome~ I will try `hal2vg`.
