### ISSUE TITLE
hal2mafMP.py  SyntaxError: leading zeros in decimal integer literals

### ISSUE THREAD

**Issue by amv33576** [ComparativeGenomicsToolkit/hal#216]
Hello, 

I am running the command:
hal2mafMP.py alignment.hal alignment.maf --refGenome Jc --numProc 10

I am getting the error: 
Traceback (most recent call last):
  File "/c1/apps/cactus/1.2.1/bin/hal2mafMP.py", line 19, in <module>
    from sonLib.bioio import system
  File "/c1/apps/mafTools/sonLib/bioio.py", line 431
    os.chmod(dirName, 0777)
                         ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

Any suggestions? 

Thanks,

Anyi

**Comment by glennhickey** [comment]
This is happening because you are using the wrong sonLib. If you're building hal yourself, you can [follow the directions here](https://github.com/ComparativeGenomicsToolkit/hal#sonlib).   But it looks like you're using Cactus, so you want to make sure your PYTHONPATH is set to pick up the sonLib included in Cactus (the procedure for this is in the Cactus installation docs)

**Comment by fransua** [comment]
Hi,
same problem here while doing `make test`, installing sonLib as suggested in hal readme: https://github.com/ComparativeGenomicsToolkit/hal/blob/master/README.md#sonlib
(removing the leading 0 in the code removes the error message)

**Comment by glennhickey** [comment]
Sorry, my above comment still stands.  This error is due to using an older version of sonLib.  The version suggested in the README is here
https://github.com/ComparativeGenomicsToolkit/sonLib/blob/master/src/sonLib/bioio.py
and it does not contain "0777"
